word_pool = list(set([
    "pickle", "giraffe", "sponge", "banana", "cheese",
    "flamingo", "ninja", "toilet", "wombat", "plunger",
    "butter", "burrito", "koala", "beaver", "marshmallow",
    "accordion", "unicorn", "pajamas", "sasquatch", "exoskeleton",
    "bubble", "dinosaur", "waffle", "potato", "pluto",
    "spork", "yodeler", "pineapple", "trombone", "afro",
    "whisk", "boomerang", "mermaid", "penguin", "pretzel",
    "toupee", "sushi", "clown", "cactus", "rubberduck",
    "cornflake", "hedgehog", "scooter", "sundae", "pogo",
    "bagel", "puppy", "butterfly", "ravioli", "gumball",
    "lollipop", "saxophone", "yogurt", "frisbee", "toaster",
    "avocado", "balloon", "moonwalk", "bowtie", "platypus",
    "trampoline", "beetle", "bongo", "doughnut", "acorn",
    "tornado", "biscuit", "caterpillar", "jigsaw", "muffin",
    "ferriswheel", "gargoyle", "clownfish", "toothpaste", "sailboat",
    "crouton", "crumpet", "wigwam", "cuckoo", "wetsuit",
    "celery", "bugle", "sesame", "eggplant", "doodle",
    "radish", "sashimi", "nachos", "raccoon", "macaroon",
    "pumpkin", "flipflop", "yak", "bumblebee", "pistachio",
    "sombrero", "croissant", "chinchilla", "slinky", "peacock",
    "milkshake", "yo-yo", "sherbet", "papaya", "watermelon",
    "gummybear", "whistle", "kiwi", "clam", "churro",
    "gazelle", "chimpanzee", "kangaroo", "lollipop", "mop",
    "dragon", "wizard", "unicorn", "elf", "sorcerer",
    "Renaissance", "Egyptian", "Medieval", "Revolution", "Victorian",
    "Paris", "Pyramids", "Colosseum", "sword", "Venice",
    "Albert Einstein", "Leonardo da Vinci", "Bernie Madoff", "Elizabeth Holmes"
]))